config/routes.rb
Rails.application.routes.draw do
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  belongs_to :cocktail
  belongs_to :ingredient
  validates_uniqueness_of :cocktail_id, scope: [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  # def new
  #   @cocktail = Cocktail.find(params[:cocktail_id])
  #   @dose = Dose.new
  # end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<%= render "utilities/nav" %>
<%= render "utilities/carousel" %>

<div class="card-deck">
  <% @cocktails.each do |cocktail| %>
    <div class="card">
   <%= image_tag("mojito.jpg" ,class: "card-img-top", width:'200', height:'350' ) %>
        <div class="card-body">
        <h5 class="card-title"><%= cocktail.name  %></h5>
<!--         <p class="card-text">Cocktails description</p> -->
        <a><%= link_to 'More', cocktail, class: "btn btn-info" %></a>
      </div>
    </div>
  <% end %>
</div>


<div class="button_container">
  <div class="row">
    <div class="col text-center">
      <%= link_to "Add a cocktail", new_cocktail_path, class:"btn btn-outline-success"%>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= render "utilities/nav" %>
<div class="new_container">
  <h2>Create a new cocktail</h2>

  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/cocktails/show.html.erb
<%= render "utilities/nav" %>
<div class="col text-center">
  <h2><%= @cocktail.name %></h2>
</div>
<div class="show_container">
  <div class="row">
      <div class="col-sm-12 col-md-6">
        <h3>Recipe</h3>
        <table class="table table-ligth">
          <tbody>
            <thead class="thead-dark">
              <th>Ingredient</th>
              <th>Description</th>
              <th>Action</th>
            </thead>
            <% @cocktail.doses.each do |dose| %>
              <tr>
                <td><%= dose.ingredient.name %></td>
                <td><%= dose.description %></td>
                <td>
                  <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                    <i class="fa fa-trash destroy_dose"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-sm-12 col-md-6">
        <%= render "doses/new" %>
      </div>
    </div>
    <div class="button_container">
      <div class="row">
        <div class="col text-center">
          <%= link_to "Back to all cocktails", cocktails_path, class:"btn btn-outline-success"%>
        </div>
      </div>
    </div>
</div>

app/views/doses/_new.html.erb
<div class="form_container">
  <h3>Add a new dose</h3>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/utilities/_carousel.html.erb
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("slide1.jpg" ,class: "d-block w-100", width:'600', height:'400' ) %>
    </div>
    <div class="carousel-item">
      <%= image_tag("slide2.jpg" ,class: "d-block w-100", width:'600', height:'400' ) %>
    </div>
    <div class="carousel-item">
      <%= image_tag("slide3.jpg" ,class: "d-block w-100", width:'600', height:'400' ) %>
    </div>
  </div>
</div>

app/views/utilities/_nav.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="">
    <%= image_tag("cocktail.svg",class:"d-inline-block align-top", width:'30', height:'30' ) %>
    MyCocktail</a>
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
</nav>